Added Project Picker View. Changes were made in Frontend and Backend
mi-classroom/mi-web-technologien-beiboot-ss2024-Amueller36 pull request #10
Opened 2024-08-27 22:30 UTC by Amueller36

2024-08-31 16:35 UTC, OliverWich requested changes
Overall für ne kleine SPA ein guter Zustand.
Ich würde nur auf jeden Fall auf dynamische imports switchen (einfach um sich später keine Sorgen drum machen zu müssen), Axios mit `fetch()` ersetzen (der Browser kann das mittlerweile sehr gut native, warum also ne dependency) und vllt mal Tools wie VueUse für Helpers, Zod für typesafety auch zur Runtime oder Iconify für schmerzfreie Icons anschauen.
Und ich würde einen Api helper basteln damit alle "magischen" keywords die man so braucht um ne richtige Api request zu bauen nur einmal irgendwo stehen und nicht bei nem späteren Change an X Stellen gefunden und ersetzt werden müssen.

(Und ja ich weiß es ist ein wenig ironisch "je weniger libraries desto besser" als Argument gegen Axios zu verwenden und dann 3 andere zu empfehlen :D Aber das eine wird native effektiv schon perfekt unterstützt und die anderen bringen wirklich hilfreiche Funktionalität)

2024-08-31 16:35 UTC, OliverWich commented on frontend/src/components/ProjectEditor.vue
>  import axios from 'axios';
Natives "fetch()" macht m.M.n. heutzutage Axios oder Ajax überflüssig für simple HTTP requests.
Eine Dependency weniger ist immer gut, und IE support ist mittlerweile eh zum Glück irrelevant.

Persönlich finde ich den fetch syntax auch etwas schöner, aber das kann einfach daran liegen, dass ich damit hauptsächlich arbeite.

2024-08-31 16:35 UTC, OliverWich commented on frontend/src/components/ProjectEditor.vue
> +interface ProjectDataResponse {
Für reines TypeScript sind Interfaces denke ich ne gute Wahl für Type safe responses.
Ich mag aber auch libraries wie [Zod](https://zod.dev/) die direkt eine Validierung mitbringen und auch zur Laufzeit Types checken was TS ja letztendlich nicht tut. Vllt mal interessant für andere Projekte, ich würd hier aber nix umstellen deswegen

2024-08-31 16:35 UTC, OliverWich commented on frontend/src/components/ProjectEditor.vue
> +  uploadedVideoUUID.value = null;
Ich nutze gerne [VueUse](https://vueuse.org/) mit den helpern für `get` und `set` fürs arbeiten mit `ref` oder `reactive`. Da muss man sich dann nicht mehr so viele Gedanken machen welcher von beiden jetzt nen `.value` braucht und welcher nicht, bzw das überhaupt zu benutzen. Gerade beim Setzen kann man das .value gerne mal vergessen, bekommt keinen type error und schon ist die reactivity weg.

Und VueUse ist generell recht praktisch, da gibts ganze Reihe an hilfreichen Tools die einem teilweise viel Arbeit abnehmen und Verwirrung vermeiden.
Oft, wenn man nen kleinen Helper braucht, macht es Sinn kurz mal bei VueUse reinzuschauen, oft haben schon genau die Richtige Funktion (die wahrscheinlich unterm Strich "besser" gebaut ist als wenn mans selber macht, gerade mit Blick auf Browser support).

2024-08-31 16:35 UTC, OliverWich commented on frontend/src/components/ProjectEditor.vue
> +  // if (!uploadedVideoUUID.value) {
Kleinigkeit, aber mit Git braucht man eigentlich keinen auskommentierten Code.

Alles was nen Kommentar ist und nicht das "Warum" für nen Block code ist kann eigentlich raus

2024-08-31 16:35 UTC, OliverWich commented on frontend/src/components/ProjectEditor.vue
> +    const response: AxiosResponse<string> = await axios.post<CreateLongExposureImageRequest, AxiosResponse<string>>(`${BACKEND_URL}/createLongExposureImage`, payload);
Ah gut, das ist natürlich ein Argument für Axios das es Generics kann und somit ordentlich getypt werden kann...
Wobei ich den Type eher für die response interessant finde und nicht für die Request. Die wird ja in dem Moment eigentlich abgegeben und nicht mehr gebraucht.

Man kann natürlich auch mit `fetch` typen, aber eben nicht über Generics

2024-08-31 16:35 UTC, OliverWich commented on frontend/src/components/ProjectEditor.vue
> +      src: `${BACKEND_URL}/outputs/${uploadedVideoUUID.value}/frames/ffout_thumbnail_${i.toString().padStart(4, '0')}.webp`,
Ich würd das aufbauen von ner URL die aufs eigene Backend zeigt evtl auslagern in nen eigenen Helper. Muss nicht direkt ne Klasse sein, aber ich habs immer gerne wenn Envs oder feste Pfade nur ein einer Stelle gebastelt werden. Wenn sich irgendwann die Api ändert muss man sonst überall im Code nach magischen Strings suchen.

Hier an der Stelle zugegeben etwas eklig einzubauen, einfach weil ein bissl am Anfang und ein bissl am Ende des Strings dynamisch ist, aber grundsätzlich ist die Idee von nem `Api` helper mit simplen Funktionen für feste Endpunkte ne gute Idee. Dann kann man auch mit Code Generation Arbeiten (falls das Backend es unterstützt) für "End to End" Typesafety

2024-08-31 16:35 UTC, OliverWich commented on frontend/src/components/ProjectPicker.vue
> +          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="white" width="18px" height="18px">
Ich würde Icons immer entweder in eigene Komponenten auslagern oder direkt ne Icon library verwenden. (Wichtig: drauf achten das die treeshaking kann, sonst kann das Bundle schnell zu groß werden xD Machen aber eigentlich fast alle heute.)

Ich bin Fan von [Iconify](https://iconify.design/docs/icon-components/vue/), da hat man Zugriff auf extrem viele, gute Icons, ohne großen Aufwand. Gerade die `mdi:` icons nutze ich sehr gerne, da die ne gute Übersichtsseite haben (https://pictogrammers.com/library/mdi/)

2024-08-31 16:35 UTC, OliverWich commented on frontend/src/components/ProjectPicker.vue
> +const BACKEND_URL = import.meta.env.VITE_BACKEND_URL;
Again, env imports, besonders für ne Backend URL hab ich gerne an der Stelle wo die URLs gebaut werden (aka einmal irgendwo in nem Helper)

2024-08-31 16:35 UTC, OliverWich commented on frontend/src/components/ProjectPicker.vue
> +/* Container styles */
Kommentare über Component Styles sind immer ne gute Idee, sonst wird das schnell sehr unübersichtlich

2024-08-31 16:35 UTC, OliverWich commented on frontend/src/components/ProjectPicker.vue
> +body {
Bei dir ist ein Component = ein "Router View". Heißt, dein Router tauscht eigentlich nur einen Component aus und der ist der gesamte Body. Daher hier okay, aber ich strukturiere meine SPAs gerne etwas anders:

Ich hab immer gerne nen extra Ordner für "Views" die dann vom Router ausgetauscht werden.
Diese Views sind zwar auch "Components", sind aber irgendwie größer. Fassen also mehrere kleinere Components zusammen und bilden einen "Abschnitt".

In meinem "components" Ordner leben dann wirklich nur Sachen, die wiederverwendet werden könnten.
Nen View ist ja immer nur einmal da und daher _eigentlich_ kein Component sondern ne Component Gruppe.
Aber das ist nur die Art und Weise wie ich das gerne Strukturiere (und ich halte mich auch nicht immer dran, wenn nen View nicht viel können muss, kommt die Funktionalität halt direkt da rein ohne nen Extra Component mit den Funktionen).

Hier tut das jetzt nicht weh und ist okay alles als component zu pflegen weil die Dateien noch recht klein sind, aber wenns größer wird, könnte das irgendwann unübersichtlich werden.

2024-08-31 16:35 UTC, OliverWich commented on frontend/src/router/index.ts
> +import ProjectEditor from '@/components/ProjectEditor.vue'
Wie oben schon gesagt, ich importiere im Router gerne nur Views, nicht direkte Components

2024-08-31 16:35 UTC, OliverWich commented on frontend/src/router/index.ts
> +      component: ProjectEditor
Bei größeren SPAs (und ehrlich gesagt benutze ich das bei default) sollte man dynamische Imports verwenden damit der Bundler besser treeshaken uns splitten kann.

Also in dem Fall aus
```js
component: ProjectEditor
```
mit nem Dynamischen Import folgendes machen:
```js
component: () => import('@/components/ProjectEditor.vue')
```

So wird kann dieser Component (falls möglich, sind noch andere Faktoren dran) in nen eigenes Bundle geworfen werden und im besten Fall laden die Seiten schneller weil nurnoch der Code mitgeladen wird, der auch wirklich benutzt wird.
Sonst kann es passieren das Komponenten zusammengeklebt werden, obwohl die garnicht gleichzeitig gebraucht werden.

2024-09-11 13:03 UTC, merged

2024-09-11 13:03 UTC, Amueller36 commented
Danke für das Review! 

Das Review wird im nächsten Issue #11 mit implementiert!